### ISSUE TITLE
- in youtube videoID

### ISSUE THREAD

**Issue by dgranosa** [f1u77y/web-media-controller#12]
When there is - in youtube videoID mpris:trackid is not being returned with playerctl metadata.
Example: https://www.youtube.com/watch?v=zuJV-DAv_wE

**Comment by f1u77y** [comment]
That's because a D-Bus object path [cannot contain](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path) dashes. I'll mangle video IDs for them to be valid parts.

Thanks for reporting.
