### ISSUE TITLE
npx grunt build fails: "Required config property "copy.undefined" missing

### ISSUE THREAD

**Issue by doronbehar** [f1u77y/web-media-controller#13]
I would like to contribute a connector for https://invidio.us, it should be very similar to YouTube's. I get this error when running `npx grunt build`:
```
Running "build" task

Running "copy:undefined" (copy) task
Verifying property copy.undefined exists in config...ERROR
>> Unable to process task.
Warning: Required config property "copy.undefined" missing. Use --force to continue.

Aborted due to warnings.
```
I couldn't find any solution when searching the web for this error. I've worked around it though for my tests with Firefox by using `npx grunt build:firefox` instead.

I still thought you should know so you'll be able to fix the `Gruntfile.js` accordingly.

**Comment by f1u77y** [comment]
Sorry, `Gruntfile.js` is a mess now. I'll try to fix it.

**Comment by doronbehar** [comment]
Thanks. As for the invidio.us support I'd like to contribute, I was wondering whether you could help me a little bit getting inside the code. I have a question:

I'm trying to understand the way a `connector` works by reading the existing ones. As I see, the most important variables in a connector are the selectors I. If I give a selector (take `nextButtonSelector` for example) a value of `div#continue` and the first link inside it will lead to the next video, should it be good enough or should I find a selector that will lead straight to a link that targets the next video?

**Comment by f1u77y** [comment]
> If I give a selector (take nextButtonSelector for example) a value of div#continue and the first link inside it will lead to the next video, should it be good enough or should I find a selector that will lead straight to a link that targets the next video?

You could see `content/base-connector.js` to make a better idea of what happens there. In this case, when `next` signal comes from outside, `connector.next()` is called. Its implementation in `base-connector.js` among other things tries to get the first element that matches `nextButtonSelector` and then tries to call `elem.click()`. If there is no `click()`able element, you could just implement `next()` from scratch in your connector.

**Comment by f1u77y** [comment]
I've also fixed `Gruntfile.js` and corresponding README info.

**Comment by doronbehar** [comment]
> I've also fixed Gruntfile.js and corresponding README info.

Cool. 

> You could see content/base-connector.js to make a better idea of what happens there. In this case, when next signal comes from outside, connector.next() is called. Its implementation in base-connector.js among other things tries to get the first element that matches nextButtonSelector and then tries to call elem.click(). If there is no click()able element, you could just implement next() from scratch in your connector.

Wonderfully explained. One more question please regarding the `mediaSelector`: I tried to set it to just `video` with the hope that it will eventually make the `playPause()` functions work just like in YouTube but it didn't work.

However, I've managed to test the `addEventListener` in the console like so:
```js
document.querySelector('video').addEventListener("pause", function(){ console.log("paused")})
```
I've also tried to use `playButtonSelector` without success while I did managed to run this in the console:
```js
document.querySelector('.vjs-play-control').click()
```
According to your explanation, both of these console tests should simulate what the extension does only with a few wrappers from `content/utils.js` right?
