### ISSUE TITLE
Question: why properties canControl, canSeek &c set to true by default

### ISSUE THREAD

**Issue by doronbehar** [f1u77y/web-media-controller#18]
Hey,

I'm writing a script using https://github.com/acrisci/playerctl (https://github.com/pavouk/lgi bindings to be precise) that unifies keybindings for the currently active player either (usually either mpv, the browser or mpd (with https://github.com/natsukagami/mpd-mpris).

I noticed that no matter if there is a tab with a supported website playing something or not, web-media-controller sets the all following properties to `true` anyway:

- [CanGoNext](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:CanGoNext)
- [CanGoPrevious](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:CanGoPrevious)
- [CanPlay](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:CanPlay)
- [CanPause](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:CanPause)
- [CanSeek](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:CanSeek)
- [CanControl](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:CanControl)

TBH, it doesn't make sense to me. The only property my script can use now in order not to try to control web-media-controller only when it actually plays something is using `PlaybackStatus` which is set to `Stopped` when nothing is playing. This is not very accurate IMO..

**Comment by f1u77y** [comment]
Feel free to reopen if the problem still exists but I believe it shouldn't.

**Comment by doronbehar** [comment]
Thanks. At first, after pulling the latest version and building the extension again, I was under the impression the problem was fixed.

Today, I noticed that after a supported website plays some media and then it's tab is closed, the mentioned properties stay `true`. It seems it doesn't suffice to make the connector constructor have these default values set to `false`..

I don't know how to reopen the issue. I think this feature was removed from @github ...

**Comment by f1u77y** [comment]
> Today, I noticed that after a supported website plays some media and then it's tab is closed, the mentioned properties stay true. It seems it doesn't suffice to make the connector constructor have these default values set to false..

Was there any other open tab with supported website? I can't reproduce this.

**Comment by doronbehar** [comment]
Oh pardon me, I've used an outdated version of the repo on my own clone and it was updated only immediately after you've closed this issue with https://github.com/f1u77y/web-media-controller/commit/bdebc08426fe67bbfecb26c8f7cb808c63d6cd43 . I haven't noticed you've tagged new versions :+1: and made further updates. 

I noticed that those new versions on your `/releases/` are just tags and somehow GitHub doens't considers them as actual releases.. Maybe you should upload artifacts with your signed addon and then they'll count?

**Comment by f1u77y** [comment]
> I noticed that those new versions on your /releases/ are just tags and somehow GitHub doens't considers them as actual releases.. Maybe you should upload artifacts with your signed addon and then they'll count?

Yes, release is separate entity from tag. I'll upload artifacts ASAP. BTW, Firefox extension is now availible [here](https://addons.mozilla.org/en-US/firefox/addon/web-media-controller/) too.
