### ISSUE TITLE
npx grunt build failes: entry.isFile is not a function

### ISSUE THREAD

**Issue by doronbehar** [f1u77y/web-media-controller#19]
Hey,

While trying to test a new connector I'd like to contribute when ready, I've encountered this error from `npx grunt build:firefox` when trying to test it:

```
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: entry.isFile is not a function
Warning: Task "build:firefox" not found. Use --force to continue.

Aborted due to warnings.
```

Could there have been an update to `fs` module that introduced a change in the API? Perhaps `package-lock.json` should be committed to the repository as well so these changes could be tracked (I'm not sure if this suggestion is right).

**Comment by doronbehar** [comment]
O.K, sorry for the disturbance  - I've had system installation issues which made me use an old version of node / npm without support for `{ withFileTypes: true }` in `fs.readdirSync`.

**Comment by f1u77y** [comment]
I still have to change minimal node.js version in `package.json` because 6.0.0 does not have this API, so thanks for pointing that out.
