### ISSUE TITLE
Would you be interested in a CONTRIBUTING.md explaining how to add support for a new website?

### ISSUE THREAD

**Issue by doronbehar** [f1u77y/web-media-controller#21]
I'd like to write one so new users will be able to contribute new connectors as I did. I was wondering if you have any specific details you'd like to include. I'm planning on explaining this mostly through my own experience while assuming the reader knows at least a little bit JavaScript.

**Comment by f1u77y** [comment]
Nice idea, but I doubt there are many people who want to contribute here.

> I was wondering if you have any specific details you'd like to include.

Sorry but I don't know what details should be included without reading some kind of draft. You could, as you've said, explain through your own experience, and then I'll add something if you miss it.
