### ISSUE TITLE
Расширение висит в статусе "Disconnected"

### ISSUE THREAD

**Issue by strangeman** [f1u77y/web-media-controller#31]
Сломалось сегодня, подозреваю что после автоапдейта на версию 0.10.0.

Linux, Firefox 69.0.2 (64-bit), Debian Sid.
wmc-mpris собран и установлен ручками, переустановить пробовал, не помогло. 

Куда копать, где логи смотреть? :)

**Comment by f1u77y** [comment]
Скорее всего смотреть никуда не надо, а дело в том, что `wmc-mpris` не последней версии. Если обновить его хотя бы до тега `v0.1.0`, то всё должно заработать.

(Да, надо бы когда-нибудь ввести версию протокола и сообщать о её нессответствии в случае оного, чтобы таких тикетов больше не было)

**Comment by strangeman** [comment]
Да, спуллить актуальный код не сообразил чего-то. Все заработало, спасибо!

**Comment by strangeman** [comment]
For non-Russian users: if you have "Disconnected" message from the plugin, just update `wmc-mpris` to version `0.1.0` or newer.
