### ISSUE TITLE
deezer connector not working

### ISSUE THREAD

**Issue by doronbehar** [f1u77y/web-media-controller#32]
Can someone please test the deezer connector? It doesn't work for me - I see the "Stopped" sign in the extension indicator..

**Comment by f1u77y** [comment]
I've rewritten Deezer connector in https://github.com/f1u77y/web-media-controller/tree/deezer-new-layout. Please test if it works fine (I've done some testing but I don't trust myself), and then I'll merge it to master.

**Comment by doronbehar** [comment]
Works!
